spring.application.name=GymProgressTracker
spring.datasource.url=jdbc:mysql://localhost:3306/gymtracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.hiddenmethod.filter.enabled=true

logging.level.org.springframework.security=DEBUG

# Wymuszenie nowoczesnego dialektu
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Wyłączenie sprawdzania metadanych, które często wiesza aplikację przy starcie
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
